//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAudioApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAudioApp.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add route.
        /// </summary>
        public static string addRoute {
            get {
                return ResourceManager.GetString("addRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change user.
        /// </summary>
        public static string changeUser {
            get {
                return ResourceManager.GetString("changeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explore mode.
        /// </summary>
        public static string explore {
            get {
                return ResourceManager.GetString("explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend support.
        /// </summary>
        public static string friend {
            get {
                return ResourceManager.GetString("friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to friend support mode.
        /// </summary>
        public static string helpMode {
            get {
                return ResourceManager.GetString("helpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to listen again.
        /// </summary>
        public static string listenagain {
            get {
                return ResourceManager.GetString("listenagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select location.
        /// </summary>
        public static string listOfRoute {
            get {
                return ResourceManager.GetString("listOfRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location list.
        /// </summary>
        public static string locations {
            get {
                return ResourceManager.GetString("locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logged.
        /// </summary>
        public static string logged {
            get {
                return ResourceManager.GetString("logged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to login.
        /// </summary>
        public static string loginmenu {
            get {
                return ResourceManager.GetString("loginmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to low vision.
        /// </summary>
        public static string lowVision {
            get {
                return ResourceManager.GetString("lowVision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next page.
        /// </summary>
        public static string nextPage {
            get {
                return ResourceManager.GetString("nextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal mode.
        /// </summary>
        public static string normal {
            get {
                return ResourceManager.GetString("normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to partially sighted.
        /// </summary>
        public static string partiallySighted {
            get {
                return ResourceManager.GetString("partiallySighted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to people around.
        /// </summary>
        public static string people {
            get {
                return ResourceManager.GetString("people", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string peoplearoundmenu {
            get {
                return ResourceManager.GetString("peoplearoundmenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to previous page.
        /// </summary>
        public static string previousPage {
            get {
                return ResourceManager.GetString("previousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to receive message.
        /// </summary>
        public static string receive {
            get {
                return ResourceManager.GetString("receive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string receivemessagemenu {
            get {
                return ResourceManager.GetString("receivemessagemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register.
        /// </summary>
        public static string register {
            get {
                return ResourceManager.GetString("register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to facebook.
        /// </summary>
        public static string registerfb {
            get {
                return ResourceManager.GetString("registerfb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register location.
        /// </summary>
        public static string registerLocation {
            get {
                return ResourceManager.GetString("registerLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        public static string route {
            get {
                return ResourceManager.GetString("route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to route.
        /// </summary>
        public static string routemenu {
            get {
                return ResourceManager.GetString("routemenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send message?.
        /// </summary>
        public static string sendMessageTitle {
            get {
                return ResourceManager.GetString("sendMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text Input.
        /// </summary>
        public static string textinput {
            get {
                return ResourceManager.GetString("textinput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smart audio.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total blindness.
        /// </summary>
        public static string totallyBlind {
            get {
                return ResourceManager.GetString("totallyBlind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use speech recognition.
        /// </summary>
        public static string usespeech {
            get {
                return ResourceManager.GetString("usespeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to register your sight type.
        /// </summary>
        public static string visionProblemMenu {
            get {
                return ResourceManager.GetString("visionProblemMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to where am I?.
        /// </summary>
        public static string where {
            get {
                return ResourceManager.GetString("where", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
